---
title: "LULCC_CH_spatial_prob_perturbations"
format: html
editor: visual
---

Scenario name abbreviations:

EI for nature: EI_NAT

EI for culture: EI_CUL

EI for society: EI_SOC

Business as usual: BAU

Growth and Extinction : GR_EX

+-------------+------------------------+----------------------------------------------------------------------------------------------------+---------------------+---------------+------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| Scenario/s  | Driver                 | Scenario statement                                                                                 | LULC class targeted | Mechanism ID  | Mechanism description                                                                                                                          | Questions/comments                                                                                                                                     |
+=============+========================+====================================================================================================+=====================+===============+================================================================================================================================================+========================================================================================================================================================+
| EI_NAT      | land management        | strong limitation of settlement growth and                                                         | Urban               | Land_fragment | reduction of urban probability in non-fragmented areas? There a range of measures of landscape fragmentation, perhaps effective mesh density?  |                                                                                                                                                        |
|             |                        | land fragmentation                                                                                 |                     |               |                                                                                                                                                |                                                                                                                                                        |
+-------------+------------------------+----------------------------------------------------------------------------------------------------+---------------------+---------------+------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| EI_SOC      | land management        | Land                                                                                               | Urban               | Build_zone    | probability of Urban transitions increased inside building zones                                                                               |                                                                                                                                                        |
|             |                        | management is spatially zoned: areas for agriculture, residence, recreation,                       |                     |               |                                                                                                                                                |                                                                                                                                                        |
|             |                        | biodiversity promotion are spatially strongly separated.                                           |                     |               |                                                                                                                                                |                                                                                                                                                        |
+-------------+------------------------+----------------------------------------------------------------------------------------------------+---------------------+---------------+------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| EI_NAT      | settlement development | Development of small towns in mountain areas with spatial restrictions for settlement development. | Urban               | Urban_elev    | Use elevation raster to identify cells in mountainous areas and increasing probability to Urban                                                | What elevation to use and what constitutes a town?                                                                                                     |
+-------------+------------------------+----------------------------------------------------------------------------------------------------+---------------------+---------------+------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| EI_NAT      | settlement development | Abandonment of settlements in remote rural areas                                                   | Urban               | Urban_rural   | Use urban/rural typology to identify urban cells in rural areas and increase probability of transition to other classes                        | What is enough urban area to be a settlement?                                                                                                          |
+-------------+------------------------+----------------------------------------------------------------------------------------------------+---------------------+---------------+------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| EI_NAT      | settlement development | No further                                                                                         | Urban               | Build_zone    | Decrease probability of transition to urban outside the building zones or increase within?                                                     |                                                                                                                                                        |
|             |                        | urban sprawl.                                                                                      |                     |               |                                                                                                                                                |                                                                                                                                                        |
+-------------+------------------------+----------------------------------------------------------------------------------------------------+---------------------+---------------+------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| EI_CUL      | settlement development | Persistence of                                                                                     | Urban               | Urban_elev    | set probability of loss of urban area above a given elevation to zero                                                                          | This maybe of limited need because the only transition from Urban is to Static and the rate of this transition in the ref scenario falls to 0% in 2050 |
|             |                        | villages in mountainous areas                                                                      |                     |               |                                                                                                                                                |                                                                                                                                                        |
+-------------+------------------------+----------------------------------------------------------------------------------------------------+---------------------+---------------+------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| EI_CUL      | settlement development | Revival of                                                                                         | Urban               | Urban_rural   | Use urban/rural typology to identify urban cells in rural areas and increase probability of transition to other classes                        |                                                                                                                                                        |
|             |                        | settlements in remote rural areas                                                                  |                     |               |                                                                                                                                                |                                                                                                                                                        |
+-------------+------------------------+----------------------------------------------------------------------------------------------------+---------------------+---------------+------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
|             |                        | No                                                                                                 |                     |               |                                                                                                                                                |                                                                                                                                                        |
|             |                        | further urban sprawl                                                                               |                     |               |                                                                                                                                                |                                                                                                                                                        |
+-------------+------------------------+----------------------------------------------------------------------------------------------------+---------------------+---------------+------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
|             |                        |                                                                                                    |                     |               |                                                                                                                                                |                                                                                                                                                        |
+-------------+------------------------+----------------------------------------------------------------------------------------------------+---------------------+---------------+------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+

Once we have edited the able to include what we want then convert it to a dataframe

```{r}
# install.packages("remotes")
remotes::install_github("alistaire47/read.so")
```

Output as interactive table

https://glin.github.io/reactable/
